# Generated by Django 5.2.7 on 2025-10-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_paper_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='published_at',
            field=models.DateField(auto_now=True, default=None),
            preserve_default=False,
        ),
    ]
