# Generated by Django 5.2.7 on 2025-10-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_paper_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
