# Generated by Django 5.2.7 on 2025-10-22 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_paper_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='abstract',
            new_name='summary',
        ),
    ]
