# Generated by Django 5.2.7 on 2025-10-22 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_abstract_paper_summary'),
        ('main', '0006_creator'),
    ]

    operations = [
    ]
