# Generated by Django 5.2.7 on 2025-10-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_merge_0005_rename_abstract_paper_summary_0006_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
