# Generated by Django 5.2.7 on 2025-10-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_creator_github_creator_instagram_creator_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
