# Generated by Django 5.2.7 on 2025-10-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name_plural': 'OTPs'},
        ),
    ]
