# Generated by Django 5.2.7 on 2025-10-25 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name_plural': 'OTPs'},
        ),
        migrations.AddField(
            model_name='paper',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.paper')),
            ],
        ),
    ]
