# Generated by Django 5.2.7 on 2025-10-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_otp_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='organization',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
