# Generated by Django 5.2.7 on 2025-10-25 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_paper_organization_alter_paper_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='citations',
            field=models.TextField(help_text='Iqtiboslar ro‘yxati kamida 50 ta belgidan iborat bo‘lishi kerak.', validators=[django.core.validators.MinLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='intro',
            field=models.TextField(help_text='Kirish qismi kamida 300 ta belgidan iborat bo‘lishi kerak.', validators=[django.core.validators.MinLengthValidator(300)]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='keywords',
            field=models.CharField(help_text='Kalit so‘zlar 10–300 belgidan iborat bo‘lishi kerak.', max_length=300, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='organization',
            field=models.CharField(blank=True, help_text='Tashkilot nomi 5–120 belgidan iborat bo‘lishi kerak.', max_length=120, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pages',
            field=models.IntegerField(blank=True, help_text='Betlar soni 3–50 oralig‘ida bo‘lishi kerak.', null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.IntegerField(choices=[(1, 'draft'), (2, 'on_process'), (3, 'declined'), (4, 'accepted')], default=1),
        ),
        migrations.AlterField(
            model_name='paper',
            name='summary',
            field=models.TextField(help_text='Qisqacha mazmun kamida 100 ta belgidan iborat bo‘lishi kerak.', validators=[django.core.validators.MinLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(help_text='Sarlavha 10–255 belgidan iborat bo‘lishi kerak.', max_length=255, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
