# Generated by Django 5.2.7 on 2025-10-25 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='pages',
            field=models.IntegerField(blank=True, help_text='Betlar soni 3–50 oralig‘ida bo‘lishi kerak.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
