# Generated by Django 5.2.7 on 2025-10-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_paper_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.IntegerField(choices=[(1, 'draft'), (2, 'on_process'), (3, 'declined'), (4, 'accepted')], default=1, help_text='Maqolaning joriy holatini tanlang.'),
        ),
    ]
