# Generated by Django 5.2.7 on 2025-10-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_otp_options_paper_paid_at_comment'),
        ('main', '0015_alter_paper_status'),
    ]

    operations = [
    ]
