# Generated by Django 5.2.7 on 2025-10-26 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_paper_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
