# Generated by Django 5.2.7 on 2025-10-26 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_delete_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='citations',
        ),
        migrations.AlterField(
            model_name='paper',
            name='intro',
            field=models.TextField(help_text='Kirish qismi kamida 100 ta belgidan iborat bo‘lishi kerak.', max_length=500, validators=[django.core.validators.MinLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='keywords',
            field=models.CharField(help_text='Kalit so‘zlar 10–300 belgidan iborat bo‘lishi kerak.', max_length=100, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='organization',
            field=models.CharField(blank=True, help_text='Tashkilot nomi 5–120 belgidan iborat bo‘lishi kerak.', max_length=120, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pages',
            field=models.IntegerField(blank=True, help_text='Betlar soni 3–50 oralig‘ida bo‘lishi kerak.', null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='summary',
            field=models.TextField(help_text='Qisqacha mazmun kamida 100 ta belgidan iborat bo‘lishi kerak.', max_length=500, validators=[django.core.validators.MinLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(help_text='Sarlavha 10–255 belgidan iborat bo‘lishi kerak.', max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
