# Generated by Django 5.2.7 on 2025-10-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(1, 'sent'), (2, 'approved'), (3, 'denied')], default=1),
        ),
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.IntegerField(choices=[(1, 'draft'), (2, 'on_process'), (3, 'declined'), (4, 'accepted'), (5, 'payment_process')], default=1, help_text='Maqolaning joriy holatini tanlang.'),
        ),
    ]
