# Generated by Django 5.2.7 on 2025-10-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_payment_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='reject_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.IntegerField(choices=[(1, 'draft'), (2, 'on_process'), (3, 'declined'), (4, 'accepted'), (5, 'payment_process'), (6, 'blocked')], default=1, help_text='Maqolaning joriy holatini tanlang.'),
        ),
    ]
