# Generated by Django 5.2.7 on 2025-10-26 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_paper_reject_count_alter_paper_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='written_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
