# Generated by Django 5.2.7 on 2025-10-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_paper_citations_alter_paper_intro_and_more'),
        ('main', '0021_comment_written_at'),
    ]

    operations = [
    ]
