# Generated by Django 5.2.7 on 2025-10-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_merge_20251026_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
