# Generated by Django 5.2.7 on 2025-10-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_customuser_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='summary',
            new_name='abstract',
        ),
        migrations.AddField(
            model_name='paper',
            name='citations',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
