# Generated by Django 5.2.7 on 2025-10-31 16:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_summary_paper_abstract_paper_citations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='citations',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='intro',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
