# Generated by Django 5.2.7 on 2025-11-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_paper_citations_alter_paper_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='certificate',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
