# Generated by Django 5.2.7 on 2025-11-01 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_paper_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.TextField(help_text='Qisqacha mazmun kamida 100 ta belgidan iborat bo‘lishi kerak.', validators=[django.core.validators.MinLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='intro',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paper',
            name='keywords',
            field=models.CharField(help_text='Kalit so‘zlar 10–300 belgidan iborat bo‘lishi kerak.', validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(help_text='Sarlavha 10–255 belgidan iborat bo‘lishi kerak.', max_length=200, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
