# Generated by Django 5.2.7 on 2025-11-01 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_paper_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(help_text='Sarlavha 1–100 belgidan iborat bo‘lishi kerak.', max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
