# Generated by Django 5.2.7 on 2025-11-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_customuser_avatar_alter_paper_title'),
        ('main', '0027_alter_paper_abstract_alter_paper_intro_and_more'),
    ]

    operations = [
    ]
