# Generated by Django 5.2.7 on 2025-11-02 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_merge_20251102_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(help_text='Sarlavha 1–100 belgidan iborat bo‘lishi kerak.', max_length=200, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
