# Generated by Django 5.2.7 on 2025-11-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_payment_check_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_accepted',
        ),
    ]
