# Generated by Django 5.2.7 on 2025-11-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_payment_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
