# Generated by Django 5.2.7 on 2025-11-02 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_paper_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.TextField(help_text='Umumiy fikr 100–2000 belgidan iborat bo‘lishi kerak.', max_length=2000, validators=[django.core.validators.MinLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='citations',
            field=models.TextField(blank=True, help_text='Foydalanilgan adabiyotlar 100–2000 belgidan iborat bo`lsin.', max_length=2000, null=True, validators=[django.core.validators.MinLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='intro',
            field=models.TextField(help_text='Kirish qismi 100-2000 ta belgidan iborat bo‘lishi kerak.', max_length=2000, validators=[django.core.validators.MinLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='keywords',
            field=models.CharField(help_text='Kalit so‘zlar 10–300 belgidan iborat bo‘lishi kerak.', max_length=100, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='organization',
            field=models.CharField(blank=True, help_text='Tashkilot nomi 1–120 belgidan iborat bo‘lishi kerak.', max_length=120, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(help_text='Sarlavha 1–100 belgidan iborat bo‘lishi kerak.', max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
